export const START_ADD_MAKRER = "START_ADD_MAKRER"; 
export const FAIL_ADD_MARKER = "FAIL_ADD_MARKER"; 
export const SUCCESS_ADD_PICKUP_MARKER = "SUCCESS_ADD_PICKUP_MARKER";
export const SUCCESS_ADD_DROPOFF_MARKER = "SUCCESS_ADD_DROPOFF_MARKER";
export const START_ADD_ROUTE = "START_ADD_ROUTE"; 
export const FAIL_ADD_ROUTE = "FAIL_ADD_ROUTE";
export const SUCCESS_ADD_ROUTE = "SUCCESS_ADD_ROUTE";



//Auth 

export const START_GET_USER = "START_GET_USER"; 
export const FAIL_GET_USER ="FAIL_GET_USER"; 
export const SUCCESS_GET_USER = "SUCCESS_GET_USER";

// TRIP request 


export const START_TRIP_REQUEST = "START_TRIP_REQUEST"; 
export const FAIL_TRIP_REQUEST = "FAIL_TRIP_REQUEST"; 
export const SUCCESS_TRIP_REQUEST = "SUCCESS_TRIP_REQUEST";

//TRIPS 
export const START_GET_TRIPS = "START_GET_TRIPS"; 
export const FAIL_GET_TRIPS = "FAIL_GET_TRIPS"; 
export const SUCCESS_GET_TRIPS = "SUCCESS_GET_TRIPS";




